_target_: pytorch_lightning.Trainer

gpus: -1

min_epochs: 1
max_epochs: 100

ckpt_path: null

# number of validation steps to execute at the beginning of the training
num_sanity_val_steps: 0
limit_val_batches: 10
